
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'


- stage: Test
  dependsOn: Build
  condition: succeded() 
  jobs:
  - job: Test
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        configuration: '--configuration $(buildConfiguration)'
        testRunTitle: 'Running Unit Tests'

- stage: Deploy
  dependsOn: Test
  condition: succeded()
  jobs:
  - job: Deploy
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'HorrorRegistry'
        repository: 'HorrorApi'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'